# Generated by Django 6.0.3 on 2026-04-07 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_nomi', models.CharField(max_length=50)),
                ('auditoriya', models.CharField(max_length=255)),
                ('start', models.TimeField()),
                ('finish', models.TimeField()),
                ('guruh', models.CharField(max_length=200)),
                ('sana', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('about_you', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magazin_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
