# Generated by Django 6.0.3 on 2026-03-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
    ]
