# Generated by Django 6.0.3 on 2026-03-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profil_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
